### ISSUE TITLE
Environmental sounds error

### ISSUE THREAD

**Issue by kcm1231** [kschuler/words-in-noise-EEG#20]
Getting an error in the ES condition

Traceback (most recent call last):
  File "/Users/kcm73/Documents/TaskProgramming/words-in-noise-EEG-FINAL/experiment_1_19_17.py", line 623, in <module>
    exp.run_experiment()
  File "/Users/kcm73/Documents/TaskProgramming/words-in-noise-EEG-FINAL/experiment_1_19_17.py", line 168, in run_experiment
    self.do_task('main staircase')
  File "/Users/kcm73/Documents/TaskProgramming/words-in-noise-EEG-FINAL/experiment_1_19_17.py", line 240, in do_task
    is_correct = self.answer_choice_period() # return is correct
  File "/Users/kcm73/Documents/TaskProgramming/words-in-noise-EEG-FINAL/experiment_1_19_17.py", line 405, in answer_choice_period
    ans = str.replace(this_answer, "_", " ")
TypeError: descriptor 'replace' requires a 'str' object but received a 'unicode'
[Finished in 2538.457s]

**Comment by kcm1231** [comment]
Hey there,

So, we just got a similar error in the A/AV conditions as well. 

Traceback (most recent call last):
  File "/Volumes/Projects-Current/SpeechPerceptionEEG_TMS/words-in-noise-EEG-FINAL/experiment_1_19_17.py", line 623, in <module>
    exp.run_experiment()
  File "/Volumes/Projects-Current/SpeechPerceptionEEG_TMS/words-in-noise-EEG-FINAL/experiment_1_19_17.py", line 168, in run_experiment
    self.do_task('main staircase')
  File "/Volumes/Projects-Current/SpeechPerceptionEEG_TMS/words-in-noise-EEG-FINAL/experiment_1_19_17.py", line 240, in do_task
    is_correct = self.answer_choice_period() # return is correct
  File "/Volumes/Projects-Current/SpeechPerceptionEEG_TMS/words-in-noise-EEG-FINAL/experiment_1_19_17.py", line 405, in answer_choice_period
    ans = str.replace(this_answer, "_", " ")
TypeError: descriptor 'replace' requires a 'str' object but received a 'bool'
[Finished in 492.406s]

**Comment by kschuler** [comment]
Was it working fine and then a ways in it stopped?  Or did it not do any of the trials?

Also, can you attach the YAML file with the word list on it?

**Comment by kcm1231** [comment]
Heya, my RA said it had gone through a bunch of trials and then just stopped. Same with the error in the ES condition.

github won't let me attache the yaml file, so i'm emailing it. Thanks!

**Comment by kschuler** [comment]
Ok, thanks.  Yes, that typically means there is a typo or weird character in the YAML flie.

**Comment by kcm1231** [comment]
Hmm ok. I've looked through the yaml file, and I can't seem to find anything. Is there a way to get it to print out what stimulus is pulling so that we know where in the yaml file to look?

Also, I know we're going to be changing how the stimuli are chosen, so maybe redoing that will help sort this out?

**Comment by kschuler** [comment]
http://www.yamllint.com/

YAML validator
